server:
  port: 8191
#spring:
 # profiles:
  #  active: native
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sovannpiseth/microservice-config-store
          search-paths: 'service-config/*service'